import json
from pathlib import Path
from typing import List, Optional
from uuid import UUID
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

# Optional imports protection for robustness
try:
    from langchain.chat_models import init_chat_model
    from langchain_core.prompts import ChatPromptTemplate

    LANGCHAIN_AVAILABLE = True
except ImportError:
    LANGCHAIN_AVAILABLE = False

try:
    from pptx import Presentation as PPTXPresentation

    PPTX_AVAILABLE = True
except ImportError:
    PPTX_AVAILABLE = False

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "Data"
DATA_DIR.mkdir(exist_ok=True)
DATA_FILE = DATA_DIR / "storage.json"

DOWNLOADS_DIR = Path.home() / "Downloads"
DOWNLOADS_DIR.mkdir(exist_ok=True)

router1 = APIRouter(prefix="/data/pptx", tags=["Presentation"])

default_system_instruction = """
You are an expert presentation designer and content strategist. Your task is to transform preloaded, web-scraped content into a clear, visually structured slide deck.

INPUT:
- Preloaded text, metadata, and extracted key points from a target website.

RULES & GOALS:
1. Executive Summary: Condense lengthy text into key takeaways—avoid long paragraphs. Use concise bullet points (maximum 3-4 bullets per slide, 6-10 words per bullet).
2. Audience Focus: Identify the core narrative and main message suitable for a professional audience.
3. Slide Structure: For each slide, provide:
   - Slide Title (Action-oriented or metric-focused)
   - Layout Type (e.g., 3-Column Comparison, Stat Callout, Problem/Solution)
   - Slide Copy (Main points, key metrics, and supporting facts)
   - Visual Suggestion (Description of relevant iconography, diagrams, or images)
4. Data Integrity: Rely strictly on the facts, statistics, and messaging found in the scraped content. Do not hallucinate external figures.
"""


def get_openrouter_key():
    import sys
    main_module = sys.modules.get('main')
    if main_module and hasattr(main_module, 'OPENROUTER_KEY'):
        return main_module.OPENROUTER_KEY
    return ""


class Slide(BaseModel):
    title: str = Field(description="Slide Title (action-oriented or metric-focused)")
    layout_type: Optional[str] = Field(description="Layout Type (e.g., Problem/Solution, Bullet List)")
    bullet_points: List[str] = Field(description="3-4 bullet points per slide body, concise")
    visual_suggestion: Optional[str] = Field(description="Description of relevant iconography, diagrams, or images")


class Presentation(BaseModel):
    title: str = Field(description="Main title of the presentation")
    slides: List[Slide] = Field(description="List of slide objects forming the deck")


class DataInput(BaseModel):
    id: UUID
    prompt: Optional[str] = None


def get_chain():
    if not LANGCHAIN_AVAILABLE:
        raise RuntimeError("LangChain dependencies are not installed.")

    base_model = init_chat_model(
        model="openai/gpt-4o-mini",
        model_provider="openai",
        base_url="https://openrouter.ai/api/v1",
        temperature=0.3,
        api_key=get_openrouter_key()
    )

    prompt_template = ChatPromptTemplate.from_messages([
        ("system", default_system_instruction),
        ("user", """
    SCRAPED WEBSITE CONTENT:
    {scraped_content}

    USER INSTRUCTIONS / TOPIC GOAL:
    {user_prompt}
    """)
    ])

    structured_llm = base_model.with_structured_output(Presentation)
    return prompt_template | structured_llm


def get_block_by_id(json_file_path: Path, target_id: str) -> dict | None:
    if not json_file_path.exists():
        return None

    try:
        with open(json_file_path, "r", encoding="utf-8") as f:
            items = json.load(f)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(items, list):
        return None

    for item in items:
        if isinstance(item, dict) and str(item.get("id")) == str(target_id):
            return item

    return None


def create_presentation(presentation_data: Presentation, file_id: str, downloads_dir: Path) -> str:
    if not PPTX_AVAILABLE:
        raise RuntimeError("python-pptx library is not installed.")

    prs = PPTXPresentation()

    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    if slide.shapes.title:
        slide.shapes.title.text = presentation_data.title
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI Presentation Builder"

    bullet_slide_layout = prs.slide_layouts[1]
    for slide_info in presentation_data.slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        if slide.shapes.title:
            slide.shapes.title.text = slide_info.title

        if len(slide.placeholders) > 1:
            tf = slide.placeholders[1].text_frame
            tf.clear()

            for idx, bullet in enumerate(slide_info.bullet_points):
                p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
                p.text = bullet
                p.level = 0

    output_path = str(downloads_dir / f"{file_id}_presentation.pptx")
    prs.save(output_path)

    return output_path


@router1.post("", status_code=status.HTTP_200_OK)
def make_powerpoint(payload: DataInput):
    target_id = str(payload.id)
    user_prompt = payload.prompt if payload.prompt and payload.prompt.strip() else "Create a comprehensive slide deck summarizing the key points."

    if not DATA_FILE.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Storage file storage.json not found in Data directory."
        )

    scraped_info = get_block_by_id(DATA_FILE, target_id)

    if not scraped_info:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No scraped info found for ID: {target_id}",
        )

    scraped_content_str = json.dumps(scraped_info, indent=2)

    try:
        chain = get_chain()
        pydantic_presentation: Presentation = chain.invoke({
            "scraped_content": scraped_content_str,
            "user_prompt": user_prompt
        })
    except RuntimeError as re:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(re)
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LLM Generation failed: {str(e)}"
        )

    file_id = scraped_info.get("id", target_id)

    try:
        exported_file_path = create_presentation(pydantic_presentation, str(file_id), DOWNLOADS_DIR)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Presentation file creation failed: {str(e)}"
        )

    return {
        "status": "success",
        "exported_file": exported_file_path,
        "presentation_data": pydantic_presentation.model_dump()
    }