import json
from pathlib import Path
from typing import List, Optional
from uuid import UUID
from fastapi import APIRouter, HTTPException, status
from langchain.chat_models import init_chat_model
from langchain_core.prompts import ChatPromptTemplate
from pptx import Presentation as PPTXPresentation
from pydantic import BaseModel, Field

entered_id = str
ID = entered_id
BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "Data"
DATA_DIR.mkdir(exist_ok=True)
DATA_FILE = DATA_DIR / "storage.json"
router1 = APIRouter(prefix="/data/pptx", tags=["Presentation"])

default_system_instruction = """
You are an expert presentation designer and content strategist. Your task is to transform preloaded, web-scraped content into a clear, visually structured slide deck.

INPUT:
- Preloaded text, metadata, and extracted key points from a target website.

RULES & GOALS:
1. Executive Summary: Condense lengthy text into key takeaways—avoid long paragraphs. Use concise bullet points (maximum 3-4 bullets per slide, 6-10 words per bullet).
2. Audience Focus: Identify the core narrative and main message suitable for a professional audience.
3. Slide Structure: For each slide, provide:
   - Slide Title (Action-oriented or metric-focused)
   - Layout Type (e.g., 3-Column Comparison, Stat Callout, Problem/Solution)
   - Slide Copy (Main points, key metrics, and supporting facts)
   - Visual Suggestion (Description of relevant iconography, diagrams, or images)
4. Data Integrity: Rely strictly on the facts, statistics, and messaging found in the scraped content. Do not hallucinate external figures.
"""


class Slide(BaseModel):
    title: str = Field(description="Slide Title (action-oriented or metric-focused)")
    layout_type: Optional[str] = Field(description="Layout Type (e.g., Problem/Solution, Bullet List)")
    bullet_points: List[str] = Field(description="3-4 bullet points per slide body, concise")
    visual_suggestion: Optional[str] = Field(description="Description of relevant iconography, diagrams, or images")


class Presentation(BaseModel):
    title: str = Field(description="Main title of the presentation")
    slides: List[Slide] = Field(description="List of slide objects forming the deck")


class DataInput(BaseModel):
    id: UUID
    prompt: Optional[str] = None


base_model = init_chat_model(
    model="openai/gpt-4o-mini",
    model_provider="openai",
    base_url="https://openrouter.ai/api/v1",
    temperature=0.3,
)

prompt_template = ChatPromptTemplate.from_messages([
    ("system", default_system_instruction),
    ("user", """
    SCRAPED WEBSITE CONTENT:
    {scraped_content}

    USER INSTRUCTIONS / TOPIC GOAL:
    {user_prompt}
    """)
])

structured_llm = base_model.with_structured_output(Presentation)
chain = prompt_template | structured_llm


def create_presentation(presentation_data: Presentation) -> str:
    prs = PPTXPresentation()

    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = presentation_data.title
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by AI Presentation Builder"

    bullet_slide_layout = prs.slide_layouts[1]
    for slide_info in presentation_data.slides:
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = slide_info.title
        tf = slide.placeholders[1].text_frame
        tf.clear()

        for idx, bullet in enumerate(slide_info.bullet_points):
            p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
            p.text = bullet
            p.level = 0

    output_path = BASE_DIR / "output.pptx"
    prs.save(output_path)

    return f"Successfully generated presentation with {len(presentation_data.slides)} slides titled '{presentation_data.title}'."


@router1.post("/powerpointmaker", status_code=status.HTTP_200_OK)
def make_powerpoint(payload: DataInput):
    target_id = str(payload.id)
    user_prompt = payload.prompt if payload.prompt and payload.prompt.strip() else "Create a comprehensive slide deck summarizing the key points."

    if not DATA_FILE.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="storage.json file not found",
        )

    with open(DATA_FILE, "r", encoding="utf-8") as r:
        try:
            items = json.load(r)
        except json.JSONDecodeError:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="storage.json contains invalid JSON",
            )

    scraped_info = next(
        (item for item in items if str(item.get("id")) == target_id), None
    )

    if not scraped_info:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"No scraped info found for ID: {target_id}",
        )

    scraped_content_str = json.dumps(scraped_info, indent=2)

    try:
        pydantic_presentation: Presentation = chain.invoke({
            "scraped_content": scraped_content_str,
            "user_prompt": user_prompt
        })
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LLM Generation failed: {str(e)}"
        )

    result_message = create_presentation(pydantic_presentation)

    return {
        "status": "success",
        "message": result_message,
        "presentation_data": pydantic_presentation.model_dump()
    }